# Generated by Django 3.1.3 on 2021-01-05 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='College Name')),
                ('code', models.IntegerField(blank=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='College Code')),
                ('chairman', models.CharField(max_length=150, verbose_name='Chairman')),
                ('established_on', models.DateField(auto_now_add=True, verbose_name='Established Name')),
            ],
        ),
    ]
